//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Version = 0;
            this.Order = new HashSet<Order>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Employee { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Fax { get; set; }
        public bool Deleted { get; set; }
        public long Version { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
