//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Secondname { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public bool UseForLogin { get; set; }
        public string Password { get; set; }
        public bool Deleted { get; set; }
        public long Version { get; set; }
        public Nullable<System.Guid> UserGroupId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
