//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitCardFactMaterial
    {
        public System.Guid Id { get; set; }
        public System.Guid LimitCardMaterialId { get; set; }
        public System.Guid MaterialId { get; set; }
        public double Count { get; set; }
        public double Price { get; set; }
    
        public virtual LimitCardMaterial LimitCardMaterial { get; set; }
        public virtual Material Material { get; set; }
    }
}
