//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitCardMaterial
    {
        public LimitCardMaterial()
        {
            this.FactMaterials = new HashSet<LimitCardFactMaterial>();
        }
    
        public System.Guid Id { get; set; }
        public int Index { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid MaterialId { get; set; }
        public string Units { get; set; }
        public double UsagePerUnits { get; set; }
        public double UsagePerOrder { get; set; }
        public double Multiplicity { get; set; }
        public double Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Material Material { get; set; }
        public virtual ICollection<LimitCardFactMaterial> FactMaterials { get; set; }
    }
}
