//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetalEDMContainer : DbContext
    {
        public MetalEDMContainer()
            : base("name=MetalEDMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<Customer> CustomerSet { get; set; }
        public DbSet<Employee> EmployeeSet { get; set; }
        public DbSet<Post> PostSet { get; set; }
        public DbSet<Operation> OperationSet { get; set; }
        public DbSet<Material> MaterialSet { get; set; }
        public DbSet<OrderGroup> OrderGroupSet { get; set; }
        public DbSet<OrderOperation> OrderOperationSet { get; set; }
        public DbSet<LimitCardMaterial> LimitCardMaterialSet { get; set; }
        public DbSet<LimitCardOperation> LimitCardOperationSet { get; set; }
        public DbSet<MetalFile> MetalFileSet { get; set; }
        public DbSet<LimitCardFactMaterial> LimitCardFactMaterialSet { get; set; }
        public DbSet<UserGroup> UserGroupSet { get; set; }
        public DbSet<SysTab> SysTabSet { get; set; }
    }
}
