//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.Version = 0;
            this.OrderOperation = new HashSet<OrderOperation>();
            this.LimitCardOperation = new HashSet<LimitCardOperation>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
        public long Version { get; set; }
    
        public virtual ICollection<OrderOperation> OrderOperation { get; set; }
        public virtual ICollection<LimitCardOperation> LimitCardOperation { get; set; }
    }
}
