//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.TechCalcMultiplier = 1D;
            this.OrderWork = new HashSet<OrderOperation>();
            this.LimitCard = new HashSet<LimitCardMaterial>();
            this.LimitCardWork = new HashSet<LimitCardOperation>();
            this.OrderDrawings = new HashSet<MetalFile>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime ReadyDate { get; set; }
        public System.DateTime AcceptedDate { get; set; }
        public string DrawingNumber { get; set; }
        public MetalTransport.ModelEx.DrawingType DrawingState { get; set; }
        public bool IsCustomerMaterial { get; set; }
        public string CustomerMaterial { get; set; }
        public System.DateTime CustomerReadyDate { get; set; }
        public System.DateTime MaterialAgreed { get; set; }
        public double TechCalcPrice { get; set; }
        public int TechCalcHour { get; set; }
        public int TechCalcMinutes { get; set; }
        public System.DateTime TechCalcPriceDate { get; set; }
        public double TechCalcMultiplier { get; set; }
        public System.DateTime TechMaterialReqDate { get; set; }
        public double DirectorExpectedPrice { get; set; }
        public int DirectorExpectedDay { get; set; }
        public System.DateTime DirectorExpectedDate { get; set; }
        public bool SalesMaterialAvailable { get; set; }
        public System.DateTime SalesMaterialAvailableDate { get; set; }
        public MetalTransport.ModelEx.PaymentType SalesPrepaymentType { get; set; }
        public MetalTransport.ModelEx.PaymentType SalesPaymentType { get; set; }
        public double SalesPrice { get; set; }
        public System.DateTime SalesPriceDate { get; set; }
        public string SalesComOfferNumber { get; set; }
        public System.DateTime SalesComOfferDate { get; set; }
        public string AccSpecifNumber { get; set; }
        public System.DateTime AccSpecifDate { get; set; }
        public string AccBillNumber { get; set; }
        public System.DateTime AccBillDate { get; set; }
        public MetalTransport.ModelEx.PaymentType AccPaymType { get; set; }
        public System.DateTime AccPaymDate { get; set; }
        public System.DateTime SalesMaterialOrderDate { get; set; }
        public System.DateTime SalesMaterialOrderReadyDate { get; set; }
        public System.DateTime DirectorOrderPlanedDate { get; set; }
        public System.DateTime OrderInManufactureDate { get; set; }
        public System.DateTime MaterialInManufactureDate { get; set; }
        public System.DateTime OrderInWorkDate { get; set; }
        public System.DateTime ManMadeDate { get; set; }
        public System.DateTime OTKProductGetDate { get; set; }
        public System.DateTime OTKProductDefectDate { get; set; }
        public string OTKProductDefectInfo { get; set; }
        public System.DateTime OTKProductCorrectDate { get; set; }
        public System.DateTime ManProductApplyDate { get; set; }
        public System.DateTime ManLimitCreateDate { get; set; }
        public System.DateTime AccCustomerInformedDate { get; set; }
        public System.DateTime AccOrderPaidDate { get; set; }
        public System.DateTime AccDocumentsToSendDate { get; set; }
        public MetalTransport.ModelEx.DeliveryType SendOrderDeliveryType { get; set; }
        public System.DateTime SendDeliveryDate { get; set; }
        public MetalTransport.ModelEx.OrderReadyType OrderReadyType { get; set; }
        public int OrderHoldDay { get; set; }
        public string OrderCorruptReason { get; set; }
        public MetalTransport.ModelEx.OrderState OrderState { get; set; }
        public Nullable<System.Guid> OrderGroupId { get; set; }
        public System.DateTime DateRec { get; set; }
        public bool Deleted { get; set; }
        public long Version { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderGroup OrderGroup { get; set; }
        public virtual ICollection<OrderOperation> OrderWork { get; set; }
        public virtual ICollection<LimitCardMaterial> LimitCard { get; set; }
        public virtual ICollection<LimitCardOperation> LimitCardWork { get; set; }
        public virtual ICollection<MetalFile> OrderDrawings { get; set; }
    }
}
