//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTab
    {
        public SysTab()
        {
            this.DataBaseVersion = 0;
        }
    
        public System.Guid Id { get; set; }
        public int DataBaseVersion { get; set; }
    }
}
